;(function () {
'use strict';

// ═══════════════════════════════════════════════════════════════════════════════
//  ComputedStats.js  —  Endless Sky Computed Ship / Outfit Statistics
//
//  Computes effective ship/outfit stats entirely from attributeDefinitions.json.
//  Zero hardcoded attribute names, formulas, or stacking rules.
//
//  PUBLIC API
//  ──────────
//  ComputedStats.init(attrDefs, baseUrl)
//  ComputedStats.isReady()  → boolean
//  ComputedStats.getComputedStats(ship, pluginId, options)  → Object
//  ComputedStats.getComputedStat(ship, pluginId, statKey, options)  → number|undefined
//  ComputedStats.getComputedStatsForAttrs(attrs, options)  → Object
//  ComputedStats.getComputedSorterFields()  → Array<{id,key,label,...}>
//  ComputedStats.clearCache()
//
//  DEPENDENCIES
//  ────────────
//  WeaponStats (window.WeaponStats) — optional, injects weapon DPS stats.
//  ComputedMovementStats (window.ComputedMovementStats) — optional, injects
//  movement stats (max velocity, turn rate, jump range, etc.) as flat
//  "_mv_*" keys. computedMovementStats.js itself wraps movementStats.js
//  (read-only dependency, never modified) and does nothing else — this file
//  is the ONLY caller of ComputedMovementStats. Like _fn_/_derived_/_sys_
//  keys, "_mv_*" keys carry raw values only; labels/units are generated by
//  whatever screen renders them, not stored here.
//  window.allData must be populated before getComputedStats is called.
//
//  ── CHANGELOG (internal-ID pass) ──────────────────────────────────────────
//  Outfit resolution previously went through _getOutfitIndex(pluginId): a
//  single MERGED, name-keyed index built by checking the SHIP's own plugin
//  first and then folding in every other loaded plugin by priority order.
//  _accumulateOutfits() looked every outfit up in that merged index by NAME
//  ONLY (`outfitIdx[outfitName]`) — it never read the `pluginId`/`internalId`
//  already recorded on each individual outfit entry (parser.js has stamped
//  these since the internal-ID pass — see outfitMapToOutputFormat), so a
//  same-named outfit from an unrelated plugin could still win the lookup
//  for a ship that never installed that plugin's copy.
//
//  Separately, `Object.entries()` on an ARRAY (the shape shipBuilder.js's
//  live `sbCurrentShip.outfits` actually uses — a list of
//  `{name,count,pluginId,internalId}` objects, not a `{name: {...}}` map)
//  yields index keys ("0","1",...) instead of outfit names, so every
//  lookup missed and outfit contributions were silently dropped entirely
//  from computed stats while actively editing a ship in the builder.
//
//  Both are fixed together here:
//    - _normaliseOutfitEntries() accepts EITHER shape and always returns
//      `{ name, qty, pluginId, internalId }` entries with the real name.
//    - _getOutfitIndexById() builds a flat, GLOBALLY-KEYED `internalId →
//      outfit` map across every loaded plugin — safe with zero collision
//      risk, since the key already encodes the plugin.
//    - _resolveOutfitScoped() prefers that exact internalId/pluginId match,
//      falling back to a direct scoped search of `window.allData[pluginId]`
//      (in case the byId index is stale), and only falls back to the old
//      merged/name-only index when no pluginId is known at all (e.g. an
//      outfit typed manually with no plugin attached).
// ═══════════════════════════════════════════════════════════════════════════════

// ── Internal state ─────────────────────────────────────────────────────────────
let _attrDefs = null;
let _cache    = {};
let _ready    = false;
let _knownDisplayFns = null;
let _byIdIndexCache  = null; // NEW: internalId -> outfit, across ALL loaded plugins

// ── Plugin / outfit index ──────────────────────────────────────────────────────
let _pluginOrder  = null;
let _indexBaseUrl = null;

// ─────────────────────────────────────────────────────────────────────────────
//  INIT
// ─────────────────────────────────────────────────────────────────────────────

function init(attrDefs, baseUrl) {
    _attrDefs        = attrDefs;
    _cache           = {};
    _knownDisplayFns = null;
    _byIdIndexCache  = null;
    _ready           = !!_attrDefs;
    if (baseUrl) _ensurePluginOrder(baseUrl);
    if (_ready)
        console.log('[ComputedStats] Ready.');
    else
        console.warn('[ComputedStats] init called without attrDefs.');
}

function isReady() { return _ready; }

// ─────────────────────────────────────────────────────────────────────────────
//  CACHE CONTROL
// ─────────────────────────────────────────────────────────────────────────────

function clearCache() {
    _cache = {};
    _byIdIndexCache = null; // NEW
    const allData = window.allData || {};
    for (const [, pluginData] of Object.entries(allData)) {
        for (const key of Object.keys(pluginData)) {
            if (key.startsWith('_mergedOutfitIndex_')) delete pluginData[key];
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  PLUGIN ORDER / OUTFIT INDEX
// ─────────────────────────────────────────────────────────────────────────────

async function _ensurePluginOrder(baseUrl) {
    if (_pluginOrder) return;
    _indexBaseUrl = baseUrl;
    try {
        const res = await fetch(`${baseUrl}/index.json`);
        if (!res.ok) { _pluginOrder = []; return; }
        const idx = await res.json();
        _pluginOrder = [];
        for (const pluginList of Object.values(idx))
            for (const { outputName } of pluginList) _pluginOrder.push(outputName);
    } catch (_) { _pluginOrder = []; }
}

function _buildSinglePluginIndex(pluginId) {
    const pluginData = window.allData?.[pluginId];
    if (!pluginData) return {};
    if (!pluginData._outfitIndex) {
        pluginData._outfitIndex = {};
        (pluginData.outfits || []).forEach(o => { if (o.name) pluginData._outfitIndex[o.name] = o; });
    }
    return pluginData._outfitIndex;
}

function _getOutfitIndex(pluginId) {
    const allData    = window.allData || {};
    const cacheKey   = `_mergedOutfitIndex_${pluginId}`;
    const pluginData = allData[pluginId];
    if (pluginData?.[cacheKey]) return pluginData[cacheKey];
    const merged       = {};
    const order        = _pluginOrder || [];
    const allPluginIds = Object.keys(allData);
    const searchOrder  = [
        pluginId,
        ...order.filter(id => id !== pluginId && allData[id]),
        ...allPluginIds.filter(id => id !== pluginId && !order.includes(id)),
    ];
    for (const pid of searchOrder) {
        const idx = _buildSinglePluginIndex(pid);
        for (const [name, outfit] of Object.entries(idx))
            if (!(name in merged)) merged[name] = outfit;
    }
    if (pluginData) pluginData[cacheKey] = merged;
    return merged;
}

/**
 * NEW. Builds (and caches) a flat `internalId -> outfit` map across EVERY
 * loaded plugin. Unlike _getOutfitIndex()'s merged/priority-ordered index,
 * this has zero collision risk — the key already encodes which plugin the
 * outfit belongs to, so two same-named outfits from different plugins get
 * two distinct entries instead of one silently shadowing the other.
 */
function _getOutfitIndexById() {
    if (_byIdIndexCache) return _byIdIndexCache;
    const allData = window.allData || {};
    const byId = {};
    for (const [pid, pluginData] of Object.entries(allData)) {
        for (const outfit of (pluginData.outfits || [])) {
            if (!outfit.name) continue;
            const internalId = outfit.internalId || outfit._internalId || `${pid}::${outfit.name}`;
            byId[internalId] = outfit;
        }
    }
    _byIdIndexCache = byId;
    return byId;
}

/**
 * NEW. Resolve one outfit entry to its actual outfit object, preferring
 * the EXACT plugin it's recorded as belonging to over any merged/ambiguous
 * name-only fallback:
 *   1. `internalId` (or `pluginId::name` derived from it) in the global
 *      byId index — the correct, unambiguous match.
 *   2. A direct scoped search of `window.allData[pluginId].outfits` — a
 *      safety net in case the byId index is somehow stale/incomplete for
 *      that plugin.
 *   3. The old merged/name-only index — ONLY when no pluginId is known at
 *      all (e.g. an outfit typed manually with no plugin attached, or
 *      pre-internalId cached data with no pluginId either).
 */
function _resolveOutfitScoped(entry, byIdIndex, mergedIdx) {
    const { name, pluginId, internalId } = entry;
    const idKey = internalId || (pluginId ? `${pluginId}::${name}` : null);
    if (idKey && byIdIndex && byIdIndex[idKey]) return byIdIndex[idKey];
    if (pluginId) {
        const pluginData = window.allData?.[pluginId];
        const found = (pluginData?.outfits || []).find(o => o.name === name);
        if (found) return found;
    }
    return (mergedIdx && mergedIdx[name]) || null;
}

/**
 * NEW. Normalises a ship's outfit list — which may be EITHER an object map
 * (`{ "Blaster": { count, pluginId, internalId } }`, the shape the parser/
 * DataViewer produce) OR an array (`[{ name, count, pluginId, internalId }]`,
 * the shape shipBuilder.js's live `sbCurrentShip.outfits` actually uses) —
 * into one consistent array of `{ name, qty, pluginId, internalId }`.
 * Previously `Object.entries()` was called directly on whatever shape was
 * passed in; for the array shape that yields index keys ("0","1",...)
 * instead of outfit names, so every lookup silently missed and outfit
 * contributions never made it into computed stats while a ship was being
 * actively edited in the builder.
 */
function _normaliseOutfitEntries(outfitSource) {
    if (!outfitSource) return [];
    const entries = [];
    if (Array.isArray(outfitSource)) {
        for (const o of outfitSource) {
            if (!o) continue;
            const name = (o.name || '').replace(/^"|"$/g, '');
            if (!name) continue;
            entries.push({
                name,
                qty: parseInt(o.count) || 1,
                pluginId: o.pluginId || null,
                internalId: o.internalId || null,
            });
        }
        return entries;
    }
    for (const [key, val] of Object.entries(outfitSource)) {
        const name = key.replace(/^"|"$/g, '');
        if (!name) continue;
        if (typeof val === 'object' && val !== null) {
            entries.push({
                name,
                qty: parseInt(val.count) || 1,
                pluginId: val.pluginId || null,
                internalId: val.internalId || null,
            });
        } else {
            entries.push({ name, qty: Number(val) || 1, pluginId: null, internalId: null });
        }
    }
    return entries;
}

// ─────────────────────────────────────────────────────────────────────────────
//  SUPPRESSION: ship functions
// ─────────────────────────────────────────────────────────────────────────────

function _getKnownDisplayFns() {
    if (_knownDisplayFns) return _knownDisplayFns;
    _knownDisplayFns = new Set();
    const fns = _attrDefs?.shipFunctions || {};
    for (const [name, fn] of Object.entries(fns)) {
        if (
            fn.attributesRead?.length &&
            fn.formulas?.length &&
            (fn.displayScale ?? 1) > 1 &&
            !/^(bool|void|string|const string|shared_ptr|vector|map|set|pair|.*[*&])/.test(fn.returnType || '')
        ) {
            _knownDisplayFns.add(name);
        }
    }
    return _knownDisplayFns;
}

function _shouldSuppressFn(fnName, fnData) {
    const ret     = (fnData.returnType || '').trim();
    const attrs   = fnData.attributesRead || [];
    const formula = fnData.formulas?.[fnData.formulas.length - 1]?.formula ?? '';

    if (/^(bool|void|string|const string|shared_ptr|vector|map|set|pair|.*[*&])/.test(ret)) return true;
    if (!fnData.formulas?.length) return true;
    if (!attrs.length) {
        const displayFns    = _getKnownDisplayFns();
        const callsDisplayFn = [...displayFns].some(fn => formula.includes(`${fn}(`));
        if (!callsDisplayFn) return true;
    }
    if (formula.includes('min(1.'))                                      return true;
    if (formula.includes('/ maximum'))                                   return true;
    if (formula && !formula.includes('[') && !formula.includes('(') &&
        /^\w+$/.test(formula.trim()))                                    return true;
    if (/^0[.\s]*$/.test(formula.trim()))                                return true;
    if (formula.includes('>= mass') && formula.includes('/ mass'))      return true;
    if (formula.includes('sqrt(') && attrs.length === 1 &&
        attrs[0].includes('cargo'))                                      return true;
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
//  SUPPRESSION: intermediate display vars
// ─────────────────────────────────────────────────────────────────────────────

function _shouldSuppressIntermediateVar(varName, formula) {
    if (/PerFrame$/i.test(varName)) return true;
    const bracketCount = (formula.match(/\[/g) || []).length;
    const hasDivision  = formula.includes('/');
    const hasFnCall    = /[A-Z][a-zA-Z]+\s*\(/.test(formula);
    const hasMaxMin    = /\bmax\s*\(|\bmin\s*\(/.test(formula);
    if (!hasDivision && !hasFnCall && !hasMaxMin && bracketCount <= 1) return true;
    if (!hasDivision && !hasFnCall && bracketCount === 2 && formula.includes('?')) return true;
    if (/^\d+\.\s*\*/.test(formula.trim())) return true;
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
//  evalFormula
// ─────────────────────────────────────────────────────────────────────────────

function _evalFormula(formulaStr, attrs, resolvedFns, localVars, solarPower) {
    if (!formulaStr || typeof formulaStr !== 'string') return NaN;
    const solar = (typeof solarPower === 'number' && !isNaN(solarPower)) ? solarPower : 1.0;

    try {
        let js = formulaStr;

        js = js.replace(/\[([^\]]+)\]/g, (_, k) => {
            const v = parseFloat((attrs || {})[k] ?? 0);
            return isNaN(v) ? '0' : String(v);
        });

        for (const [fn, val] of Object.entries(resolvedFns || {})) {
            const escaped = fn.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
            js = js.replace(new RegExp('\\b' + escaped + '\\s*\\(\\s*\\)', 'g'), '(' + String(val) + ')');
        }

        if (localVars && Object.keys(localVars).length > 0) {
            const sorted = Object.entries(localVars).sort((a, b) => b[0].length - a[0].length);
            for (const [varName, val] of sorted) {
                const escaped = varName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
                js = js.replace(
                    new RegExp('\\b' + escaped + '\\b(?!\\s*[\\[(])', 'g'),
                    '(' + String(val) + ')'
                );
            }
        }

        js = js.replace(/\b(max|min)<[^>]+>\s*\(/g, '__MATH_$1__(');
        js = js.replace(/static_cast<[^>]+>\s*\(([^)]+)\)/g, '($1)');

        const massVal = String(parseFloat((attrs || {})['mass'] ?? 0));
        const eCap    = String(parseFloat((attrs || {})['energy capacity'] ?? 0));
        const fCap    = String(parseFloat((attrs || {})['fuel capacity'] ?? 0));
        const coolEff = resolvedFns?.['CoolingEfficiency'] != null
                          ? String(resolvedFns['CoolingEfficiency']) : '1';
        const minHull = String(
            parseFloat((attrs || {})['threshold percentage'] ?? 0) *
            parseFloat((attrs || {})['hull'] ?? 0)
        );

        js = js
            .replace(/\bMAXIMUM_TEMPERATURE\b/g,  '100')
            .replace(/numeric_limits<[^>]+>::max\(\)/g, '1e308')
            .replace(/cargo\.Used\(\)/g,           '0')
            .replace(/attributes\.Mass\(\)/g,      massVal)
            .replace(/\bcarriedMass\b/g,           '0')
            .replace(/(?<![[\w])\bmass\b(?!["\]\w])/g, massVal)
            .replace(/\bsolar_power\b/g,           String(solar))
            .replace(/\bwithAfterburner\b/g,       '0')
            .replace(/\bslowness\b/g,              '0')
            .replace(/\bdisruption\b/g,            '0')
            .replace(/\bionization\b/g,            '0')
            .replace(/\bscrambling\b/g,            '0')
            .replace(/\bhullDelay\b/g,             '0')
            .replace(/\bshieldDelay\b/g,           '0')
            .replace(/\bminimumHull\b/g,           minHull)
            .replace(/\bcoolingEfficiency\b/g,     coolEff);

        js = js
            .replace(/(?<![a-zA-Z\[])\benergy\b(?!\s*(capacity|generation|consumption|protection|damage|multiplier|[a-zA-Z\]]))/g, eCap)
            .replace(/(?<![a-zA-Z\[])\bfuel\b(?!\s*(capacity|generation|consumption|protection|damage|energy|heat|[a-zA-Z\]]))/g, fCap);

        js = js
            .replace(/\bMax\s*\(/g,   'Math.max(')
            .replace(/\bmin\s*\(/g,   'Math.min(')
            .replace(/\bmax\s*\(/g,   'Math.max(')
            .replace(/\bexp\s*\(/g,   'Math.exp(')
            .replace(/\bfloor\s*\(/g, 'Math.floor(')
            .replace(/\bsqrt\s*\(/g,  'Math.sqrt(')
            .replace(/\babs\s*\(/g,   'Math.abs(')
            .replace(/\bpow\s*\(/g,   'Math.pow(')
            .replace(/\blog\s*\(/g,   'Math.log(');

        js = js.replace(/\b(?!Math\b)[A-Za-z_][A-Za-z0-9_:]*(?:->|\.)[A-Za-z_][A-Za-z0-9_]*\s*\([^)]*\)/g, '0');
        js = js.replace(/\b(?!Math\b)[A-Z][a-zA-Z]+\s*\(\s*\)/g, '0');
        js = js.replace(/\b(?!Math\b|return\b|true\b|false\b|Infinity\b)[a-z][a-zA-Z_]*\b(?!\s*[\[(])/g, '0');

        js = js.replace(/__MATH_(max|min)__\(/g, 'Math.$1(');

        // eslint-disable-next-line no-new-func
        const result = Function('"use strict"; return (' + js + ');')();
        return typeof result === 'number' && isFinite(result) ? result : NaN;
    } catch (_) {
        return NaN;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
//  resolveLocalVars
// ─────────────────────────────────────────────────────────────────────────────

function _resolveLocalVars(attributeVariables, attrs, resolvedFns, solarPower) {
    const localVals = {};
    if (!attributeVariables || !Object.keys(attributeVariables).length) return localVals;

    const sorted = Object.entries(attributeVariables).sort((a, b) => b[0].length - a[0].length);
    let changed = true;
    let passes  = 0;
    const MAX_PASSES = sorted.length + 2;

    while (changed && passes < MAX_PASSES) {
        changed = false;
        passes++;
        for (const [varName, formula] of sorted) {
            const val = _evalFormula(formula, attrs, resolvedFns, localVals, solarPower);
            if (!isNaN(val) && isFinite(val)) {
                const prev = localVals[varName];
                if (prev === undefined || Math.abs(val - (prev ?? NaN)) > 1e-12) {
                    localVals[varName] = val;
                    changed = true;
                }
            }
        }
    }
    return localVals;
}

// ─────────────────────────────────────────────────────────────────────────────
//  accumulateOutfits
// ─────────────────────────────────────────────────────────────────────────────

/**
 * FIXED (internal-ID pass). `outfitSource` is normalised via
 * _normaliseOutfitEntries() so BOTH shapes (object map from the parser/
 * DataViewer, array from shipBuilder.js's live edit state) work correctly
 * and yield real outfit names, not index keys. Each entry is then resolved
 * via _resolveOutfitScoped(), which prefers the entry's own recorded
 * plugin (via internalId/pluginId) over the old merged/name-only fallback
 * (`outfitIdx`), which is now used only as a last resort.
 */
function _accumulateOutfits(baseAttrs, outfitSource, outfitIdx, byIdIndex) {
    const attrDefs = _attrDefs?.attributes || {};
    const result   = {};
    for (const [key, val] of Object.entries(baseAttrs))
        if (typeof val === 'number') result[key] = val;

    const entries = _normaliseOutfitEntries(outfitSource);
    let totalCount = 0;

    for (const entry of entries) {
        const qty = entry.qty;
        totalCount += qty;

        const outfit = _resolveOutfitScoped(entry, byIdIndex, outfitIdx);
        if (!outfit) continue;

        const META_KEYS = new Set([
            'name','category','series','index','cost','thumbnail','sprite',
            'description','pluginId','internalId','governments','locations',
            'weapon',
            '_internalId','_pluginId','_hash',
        ]);
        const outfitAttrs = Object.fromEntries(
            Object.entries(outfit).filter(([k, v]) => typeof v === 'number' && !META_KEYS.has(k))
        );

        for (const [key, rawVal] of Object.entries(outfitAttrs)) {
            if (typeof rawVal !== 'number') continue;
            if (key.startsWith('_'))        continue;
            const stacking = attrDefs[key]?.stacking || 'additive';
            const contrib  = rawVal * qty;
            switch (stacking) {
                case 'maximum':              result[key] = Math.max(result[key] ?? -Infinity, contrib); break;
                case 'minimum':              result[key] = Math.min(result[key] ??  Infinity, contrib); break;
                case 'additive-then-multiply': /* falls through */
                default:                     result[key] = (result[key] || 0) + contrib; break;
            }
        }
        if (typeof outfit.cost === 'number')
            result['_totalOutfitCost'] = (result['_totalOutfitCost'] || 0) + outfit.cost * qty;
        if (typeof outfit.mass === 'number')
            result['_outfitMass'] = (result['_outfitMass'] || 0) + outfit.mass * qty;
    }
    result['_totalOutfits'] = totalCount;
    return result;
}

// ─────────────────────────────────────────────────────────────────────────────
//  resolveShipFunctions
// ─────────────────────────────────────────────────────────────────────────────

function _resolveShipFunctions(attrs, solarPower) {
    const fns   = _attrDefs?.shipFunctions || {};
    const solar = (typeof solarPower === 'number') ? solarPower
                : (_attrDefs?.systemContext?.referenceSolarPower ?? 1.0);
    const cache = {};
    const done  = new Set();

    function resolveOne(fnName) {
        const fn = fns[fnName];
        if (!fn?.formulas?.length) return NaN;
        const formula   = fn.formulas[fn.formulas.length - 1].formula;
        const localVars = _resolveLocalVars(fn.attributeVariables || {}, attrs, cache, solar);
        return _evalFormula(formula, attrs, cache, localVars, solar);
    }

    const PRIORITY = [
        'Mass', 'Drag', 'DragForce', 'InertialMass',
        'CoolingEfficiency', 'HeatDissipation', 'MaximumHeat',
        'MaxShields', 'MaxHull', 'MinimumHull',
        'TurnRate', 'Acceleration', 'MaxVelocity',
        'ReverseAcceleration', 'MaxReverseVelocity',
        'IdleHeat',
        'CloakingSpeed', 'RequiredCrew', 'CrewValue',
    ];

    for (const fnName of PRIORITY) {
        const val = resolveOne(fnName);
        if (fnName === 'CoolingEfficiency' && (isNaN(val) || val < 0 || val > 2.5)) {
            const x = parseFloat((attrs || {})['cooling inefficiency'] ?? 0);
            cache['CoolingEfficiency'] = 2 + 2 / (1 + Math.exp(x / -2)) - 4 / (1 + Math.exp(x / -4));
        } else if (!isNaN(val)) {
            cache[fnName] = val;
        }
        done.add(fnName);
    }

    let madeProgress = true;
    while (madeProgress) {
        madeProgress = false;
        for (const fnName of Object.keys(fns)) {
            if (done.has(fnName)) continue;
            const fn = fns[fnName];
            if (!fn?.formulas?.length) { done.add(fnName); continue; }
            const val = resolveOne(fnName);
            if (!isNaN(val)) {
                const prev = cache[fnName];
                cache[fnName] = val;
                done.add(fnName);
                if (prev !== val) madeProgress = true;
            }
        }
    }

    return cache;
}

// ─────────────────────────────────────────────────────────────────────────────
//  resolveDerivedValues
// ─────────────────────────────────────────────────────────────────────────────

function _resolveDerivedValues(attrs, fnCache, solarPower) {
    const derived  = {};
    const display  = _attrDefs?.shipDisplay || {};
    const intVars  = display.intermediateVars || {};
    const table    = display.energyHeatTable  || [];
    const solar    = (typeof solarPower === 'number') ? solarPower
                   : (_attrDefs?.systemContext?.referenceSolarPower ?? 1.0);
    const varCache = { ...fnCache };

    const resolvedVars = new Set();
    let changed = true;
    let pass    = 0;
    const maxPasses = Object.keys(intVars).length + 1;

    while (changed && pass < maxPasses) {
        changed = false; pass++;
        for (const [varName, formula] of Object.entries(intVars)) {
            if (resolvedVars.has(varName)) continue;
            if (_shouldSuppressIntermediateVar(varName, formula)) continue;
            const val = _evalFormula(formula, attrs, varCache, {}, solar);
            if (!isNaN(val) && isFinite(val)) {
                const prev = varCache[varName];
                varCache[varName] = val;
                derived[`_derived_${varName}`] = val;
                resolvedVars.add(varName);
                if (prev === undefined || Math.abs(val - prev) > 1e-10) changed = true;
            }
        }
    }

    // Energy/heat table rows. Previously gated on `eVal !== 0`/`hVal !== 0`,
    // which meant a value that computed to EXACTLY zero (e.g. two outfits'
    // contributions cancelling out) was dropped from `derived` entirely —
    // no key at all, so nothing downstream could ever show it, not even as
    // "0". Relevance filtering already happens elsewhere, on a completely
    // different (and correct) basis: ItemStats.js's filterComputedStats
    // only keeps a `_derived_*` key when the ship/outfit's own attributes
    // actually reference one of the formula's driving keys AT ALL (i.e. the
    // attribute is genuinely present, regardless of its value) — so a ship
    // with no capability in this area at all is still filtered out
    // downstream, exactly as before. Only the VALUE-based zero-suppression
    // here — which had no way to distinguish "never relevant" from
    // "relevant but happens to net to zero" — needed to go.
    for (const row of table) {
        if (!row.label) continue;
        const eVal = _evalFormula(row.energyFormula, attrs, varCache, {}, solar);
        const hVal = _evalFormula(row.heatFormula,   attrs, varCache, {}, solar);
        const safeLabel = row.label.replace(/[^a-zA-Z0-9]/g, '_');
        if (!isNaN(eVal)) derived[`_derived_energy_${safeLabel}`] = eVal;
        if (!isNaN(hVal)) derived[`_derived_heat_${safeLabel}`]   = hVal;
    }

    const fns = _attrDefs?.shipFunctions || {};
    for (const [fnName, fnData] of Object.entries(fns)) {
        if (fnCache[fnName] === undefined) continue;
        if (_shouldSuppressFn(fnName, fnData)) continue;
        derived[`_fn_${fnName}`] = fnCache[fnName];
    }

    // Same reasoning as the energy/heat table above — system-aware formulas
    // (solar collection, ramscoop) are relevance-filtered downstream by
    // attribute presence, not by their computed value, so a zero result
    // should still be included here rather than silently dropped.
    const sysFormulas = _attrDefs?.systemAwareFormulas || {};
    for (const [attrKey, info] of Object.entries(sysFormulas)) {
        const val = _evalFormula(info.formula, attrs, varCache, {}, solar);
        if (!isNaN(val))
            derived[`_sys_${attrKey.replace(/\s+/g, '_')}`] = val * (info.displayScale ?? 1);
    }

    return derived;
}

// ─────────────────────────────────────────────────────────────────────────────
//  MOVEMENT STATS — merges in window.ComputedMovementStats output, if present
// ─────────────────────────────────────────────────────────────────────────────
//
// computedMovementStats.js wraps movementStats.js (read-only dependency,
// never modified) and does nothing beyond flattening its output into flat
// "_mv_*" keys. This function is the ONLY caller of ComputedMovementStats —
// nothing else in the app should call it directly, mirroring how nothing
// else computes _fn_/_derived_ values except this file.
//
// A no-op if ComputedMovementStats isn't loaded or isn't ready, so existing
// behaviour is completely unaffected when movement stats aren't available.
function _mergeMovementStats(attrs, target) {
    if (typeof window === 'undefined') return;
    if (!window.ComputedMovementStats?.isReady?.()) return;
    try {
        Object.assign(target, window.ComputedMovementStats.getMovementStats(attrs));
    } catch (_) { /* movement stats are best-effort — never break computed stats */ }
}

// ─────────────────────────────────────────────────────────────────────────────
//  getComputedStats  —  main public API
// ─────────────────────────────────────────────────────────────────────────────

function getComputedStats(ship, pluginId, options) {
    const id       = ship._internalId || ship.name;
    const cacheKey = id + (pluginId || '') + (options?.solarPower ?? '');
    if (_cache[cacheKey]) return _cache[cacheKey];

    const solar     = options?.solarPower
                    ?? _attrDefs?.systemContext?.referenceSolarPower
                    ?? 1.0;
    const baseAttrs = ship.attributes || {};
    const outfitIdx = _getOutfitIndex(pluginId);
    const byIdIndex = _getOutfitIndexById(); // NEW
    const result    = _accumulateOutfits(baseAttrs, ship.outfitMap || ship.outfits || {}, outfitIdx, byIdIndex);

    for (const [key, val] of Object.entries(ship))
        if (typeof val === 'number' && !key.startsWith('_') && !(key in result)) result[key] = val;

    const fnCache = _resolveShipFunctions(result, solar);
    const derived = _resolveDerivedValues(result, fnCache, solar);
    Object.assign(result, derived);

    if (typeof window.WeaponStats !== 'undefined') {
        const outfitMap = ship.outfitMap || ship.outfits || {};
        const wsFlat    = window.WeaponStats.resolveWeaponStats(outfitMap, outfitIdx);
        Object.assign(result, wsFlat);
        Object.defineProperty(result, '_weaponStats', {
            value:        wsFlat['_weaponStats'],
            enumerable:   false,
            writable:     true,
            configurable: true,
        });
        delete result['_weaponStats'];
    }

    // Movement stats (max velocity, turn rate, jump range, fuel/jump, cloak
    // timing, ...) — computed from the same accumulated attrs used above, so
    // they reflect this ship's actual installed outfits. See _mergeMovementStats.
    _mergeMovementStats(result, result);

    _cache[cacheKey] = result;
    return result;
}

function getComputedStat(ship, pluginId, statKey, options) {
    return getComputedStats(ship, pluginId, options)?.[statKey];
}

// ─────────────────────────────────────────────────────────────────────────────
//  getComputedSorterFields
// ─────────────────────────────────────────────────────────────────────────────

function getComputedSorterFields() {
    if (!_attrDefs) return [];
    const fields  = [];
    const display = _attrDefs.shipDisplay || {};
    const intVars = display.intermediateVars || {};
    const fns     = _attrDefs.shipFunctions || {};

    for (const [varName, formula] of Object.entries(intVars)) {
        if (_shouldSuppressIntermediateVar(varName, formula)) continue;
        const id    = `_derived_${varName}`;
        const label = varName.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()).trim() + ' (computed)';
        fields.push({ id, key: id, label, path: null, isComputed: true });
    }
    for (const row of (display.energyHeatTable || [])) {
        if (!row.label) continue;
        const safeLabel = row.label.replace(/[^a-zA-Z0-9]/g, '_');
        const baseLabel = row.label.charAt(0).toUpperCase() + row.label.slice(1);
        fields.push({ id: `_derived_energy_${safeLabel}`, key: `_derived_energy_${safeLabel}`, label: `${baseLabel} Energy/s (computed)`, path: null, isComputed: true });
        fields.push({ id: `_derived_heat_${safeLabel}`,   key: `_derived_heat_${safeLabel}`,   label: `${baseLabel} Heat/s (computed)`,   path: null, isComputed: true });
    }
    for (const [fnName, fnData] of Object.entries(fns)) {
        if (_shouldSuppressFn(fnName, fnData)) continue;
        const id    = `_fn_${fnName}`;
        const label = fnName.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()).trim() + ' (computed)';
        fields.push({ id, key: id, label, path: null, isComputed: true });
    }
    for (const [attrKey, info] of Object.entries(_attrDefs?.systemAwareFormulas || {})) {
        const id    = `_sys_${attrKey.replace(/\s+/g, '_')}`;
        const label = attrKey.split(' ').map(w => w[0].toUpperCase() + w.slice(1)).join(' ') + ' (system)';
        fields.push({ id, key: id, label, path: null, isComputed: true, isSystemAware: true });
    }
    const wsLabels = {
        '_ws_totalDps':    'Total DPS (computed)',
        '_ws_shieldDps':   'Shield DPS (computed)',
        '_ws_hullDps':     'Hull DPS (computed)',
        '_ws_weaponCount': 'Weapon Types (computed)',
    };
    for (const [id, label] of Object.entries(wsLabels))
        fields.push({ id, key: id, label, path: null, isComputed: true });

    return fields;
}

// ─────────────────────────────────────────────────────────────────────────────
//  getComputedStatsForAttrs  —  bare attribute map (no outfit accumulation)
// ─────────────────────────────────────────────────────────────────────────────

function getComputedStatsForAttrs(attrs, options) {
    const solar   = options?.solarPower ?? _attrDefs?.systemContext?.referenceSolarPower ?? 1.0;
    const fnCache = _resolveShipFunctions(attrs, solar);
    const derived = _resolveDerivedValues(attrs, fnCache, solar);
    const result  = { ...attrs, ...derived };
    _mergeMovementStats(attrs, result);
    return result;
}

// ─────────────────────────────────────────────────────────────────────────────
//  DEBUG HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function debugComputedStats(pluginId, shipName) {
    const plugin = window.allData?.[pluginId];
    if (!plugin) { console.error('Plugin not found:', pluginId); return; }
    const ship = (plugin.ships || []).find(s => s.name === shipName)
              || (plugin.variants || []).find(s => s.name === shipName);
    if (!ship) { console.error('Ship not found:', shipName); return; }
    if (!_attrDefs) { console.error('attrDefs not loaded'); return; }
    const stats = getComputedStats(ship, pluginId);
    console.group(`ComputedStats: ${shipName}`);
    console.log('_fn_ keys:', Object.keys(stats).filter(k => k.startsWith('_fn_')));
    console.log('_derived_ keys:', Object.keys(stats).filter(k => k.startsWith('_derived_')));
    console.log('_sys_ keys:', Object.keys(stats).filter(k => k.startsWith('_sys_')));
    console.log('_mv_ keys:', Object.keys(stats).filter(k => k.startsWith('_mv_')));
    console.groupEnd();
    return stats;
}

function debugFnResolution(pluginId, shipName) {
    const plugin = window.allData?.[pluginId];
    const ship   = (plugin?.ships || []).find(s => s.name === shipName);
    if (!ship || !_attrDefs) { console.error('Ship or attrDefs not found'); return; }
    const outfitIdx = _getOutfitIndex(pluginId);
    const byIdIndex = _getOutfitIndexById();
    const attrs     = _accumulateOutfits(ship.attributes || {}, ship.outfitMap || {}, outfitIdx, byIdIndex);
    const solar     = _attrDefs?.systemContext?.referenceSolarPower ?? 1.0;
    const fns       = _attrDefs.shipFunctions || {};
    const PRIORITY  = [
        'Mass','Drag','InertialMass','CoolingEfficiency','HeatDissipation',
        'MaximumHeat','MaxShields','MaxHull','TurnRate','Acceleration','MaxVelocity',
        'IdleHeat','CloakingSpeed',
    ];
    const testCache = {};
    console.group(`FnResolution: ${shipName}`);
    for (const fnName of PRIORITY) {
        const fn = fns[fnName];
        if (!fn?.formulas?.length) { console.log(`  ${fnName}: no formulas`); continue; }
        const localVars = _resolveLocalVars(fn.attributeVariables || {}, attrs, testCache, solar);
        const formula   = fn.formulas[fn.formulas.length - 1].formula;
        const val       = _evalFormula(formula, attrs, testCache, localVars, solar);
        const scale     = fn.displayScale ?? 1;
        const sup       = _shouldSuppressFn(fnName, fn);
        console.log(`  ${fnName}: raw=${val?.toFixed(4)}  display=${(val * scale)?.toFixed(4)}  suppressed=${sup}`);
        console.log(`    formula: ${formula}`);
        if (Object.keys(localVars).length) console.log(`    localVars:`, localVars);
        if (!isNaN(val)) testCache[fnName] = val;
    }
    console.groupEnd();
}

function debugOutfitStats(pluginId, outfitName) {
    const plugin = window.allData?.[pluginId];
    if (!plugin || !_attrDefs) { console.error('Plugin or attrDefs not found'); return; }
    const outfit = (plugin.outfits || []).find(o => o.name === outfitName);
    if (!outfit) { console.error('Outfit not found:', outfitName); return; }
    const attrs  = outfit.attributes ?? {};
    const result = getComputedStatsForAttrs(attrs);
    console.group(`OutfitStats: ${outfitName}`);
    console.log('fn_ keys:', Object.keys(result).filter(k => k.startsWith('_fn_')));
    console.log('All attrs:', attrs);
    console.groupEnd();
    return result;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  PUBLIC EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

window.ComputedStats = {
    init,
    isReady,
    getComputedStats,
    getComputedStat,
    getComputedStatsForAttrs,
    getComputedSorterFields,
    clearCache,
    debugComputedStats,
    debugFnResolution,
    debugOutfitStats,
    _evalFormula,
    _resolveShipFunctions,
    _resolveLocalVars,
    _accumulateOutfits,
    _shouldSuppressFn,
    _shouldSuppressIntermediateVar,
};

window.initComputedStats        = init;
window.clearComputedCache       = clearCache;
window.getComputedStats         = getComputedStats;
window.getComputedStat          = getComputedStat;
window.getComputedSorterFields  = getComputedSorterFields;
window.getComputedStatsForAttrs = getComputedStatsForAttrs;
window.debugComputedStats       = debugComputedStats;
window.debugFnResolution        = debugFnResolution;
window.debugOutfitStats         = debugOutfitStats;

if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.ComputedStats;
}

})();
